#!/bin/bash
export PATH="/bin:/sbin:/usr/sbin:/usr/bin"

OLDGW=`ip route show |grep 'eth' | grep '^default' | sed -e 's/default via \([^ ]*\).*/\1/' |head -1`

if [ $OLDGW == '' ]; then
    exit 0
fi

if [ ! -e /tmp/vpn_oldgw ]; then
    echo $OLDGW > /tmp/vpn_oldgw
fi


route add -net 1.0.1.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.0.2.0 netmask 255.255.254.0 gw $OLDGW
route add -net 1.0.8.0 netmask 255.255.248.0 gw $OLDGW
route add -net 1.0.32.0 netmask 255.255.224.0 gw $OLDGW
route add -net 1.1.0.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.1.2.0 netmask 255.255.254.0 gw $OLDGW
route add -net 1.1.4.0 netmask 255.255.252.0 gw $OLDGW
route add -net 1.1.8.0 netmask 255.255.248.0 gw $OLDGW
route add -net 1.1.16.0 netmask 255.255.240.0 gw $OLDGW
route add -net 1.1.32.0 netmask 255.255.224.0 gw $OLDGW
route add -net 1.2.0.0 netmask 255.255.254.0 gw $OLDGW
route add -net 1.2.2.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.2.4.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.2.5.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.2.6.0 netmask 255.255.254.0 gw $OLDGW
route add -net 1.2.8.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.2.9.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.2.10.0 netmask 255.255.254.0 gw $OLDGW
route add -net 1.2.12.0 netmask 255.255.252.0 gw $OLDGW
route add -net 1.2.16.0 netmask 255.255.240.0 gw $OLDGW
route add -net 1.2.32.0 netmask 255.255.224.0 gw $OLDGW
route add -net 1.2.64.0 netmask 255.255.192.0 gw $OLDGW
route add -net 1.3.0.0 netmask 255.255.0.0 gw $OLDGW
route add -net 1.4.1.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.4.2.0 netmask 255.255.254.0 gw $OLDGW
route add -net 1.4.4.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.4.5.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.4.6.0 netmask 255.255.254.0 gw $OLDGW
route add -net 1.4.8.0 netmask 255.255.248.0 gw $OLDGW
route add -net 1.4.16.0 netmask 255.255.240.0 gw $OLDGW
route add -net 1.4.32.0 netmask 255.255.224.0 gw $OLDGW
route add -net 1.4.64.0 netmask 255.255.192.0 gw $OLDGW
route add -net 1.8.0.0 netmask 255.255.0.0 gw $OLDGW
route add -net 1.10.0.0 netmask 255.255.248.0 gw $OLDGW
route add -net 1.10.8.0 netmask 255.255.254.0 gw $OLDGW
route add -net 1.10.11.0 netmask 255.255.255.0 gw $OLDGW
route add -net 1.10.12.0 netmask 255.255.252.0 gw $OLDGW
route add -net 1.10.16.0 netmask 255.255.240.0 gw $OLDGW
route add -net 1.10.32.0 netmask 255.255.224.0 gw $OLDGW
route add -net 1.10.64.0 netmask 255.255.192.0 gw $OLDGW
route add -net 1.12.0.0 netmask 255.252.0.0 gw $OLDGW
route add -net 1.24.0.0 netmask 255.248.0.0 gw $OLDGW
